# Generated by Django 4.2.5 on 2023-10-12 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_rename_area_atuacao_autormodels_especializacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitamodels',
            name='autor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='receita.autormodels'),
        ),
    ]
