# Generated by Django 4.2.5 on 2023-10-12 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0004_alter_receitamodels_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receitamodels',
            old_name='autor',
            new_name='autor_id',
        ),
    ]
